spring:
  application:
    name: spring-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webmvc: # Use the full path to avoid deprecation warnings
          routes:
            - id: payment-init-route
              uri: http://localhost:8080
              predicates:
                - Path=/api/payInit
              filters:
                - RewritePath=/api/payInit, /payInit
                - name: CircuitBreaker
                  args:
                    id: exampleCB
                    statusCodes: 500, 503
resilience4j.circuitbreaker:
  instances:
      exampleCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        sliding-window-type: COUNT_BASED
        baseConfig: default
  configs:
    default:
      register-health-indicator: true
management:
  endpoints:
    web:
      exposure:
        include: "health,beans,info" # Plural 'beans'
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true
